name: exemplary_pipeline
channels:
- conda-forge
- bioconda
dependencies:
- python >= 3.11
- bioconda/noarch::snakemake >= 7.25.0
- pandas
- scipy
- ipython >= 8.10.0
- r-base >= 4.2.0
- r-data.table >= 1.14.8
- r-magrittr
- r-stringr
